### PR TITLE
Openthread FTD, MTD and NCP

### PR DESCRIPTION
**Pull request by biboc**
Add support for OpenThread FTD (Full Thread Device), MTD (Minimal Thread Device) and NCP (Network Co-Processor) device
Apply correction from aabadie review

Known bug:
. After a while an FTD catches an assert
. A MTD does not manage to connect to a FTD on SAMR21

### CODE REVIEW

**Comment by jia200x** [comment]
awesome. Did you manage to make wpantund work with the NCP example?

And thank you so much for addressing all those issues.
Cheers

**Comment by biboc** [comment]
Yes I did by UART
Wpantund on Ubuntu 16.04 + openthread_test_ncp on samr21-explained pro board

I still have both issue I mentioned in the PR.
Please try to run openthread_test_ftd on a node and openthread_test_mtd on
another one and tell me what you get. For me MTD device can't connect to
FTD and FTD don't want to send some frame because they are too long.

I'll try tomorrow to compile in native.

**Comment by biboc** [comment]
By the way, I didn't try to recompile your examples (openthread and openthread_sock_udp). I'll try tomorrow, I think you just need to edit the Makefile.

Also I can't make it compile in native yet

**Comment by biboc** [comment]
By the way I really don't understand why we use sock_udp here? We don't need UDP at all since OpenThread has a UDP layer. Name of the file seems wrong?

**Comment by jia200x** [comment]
Hi.

As said via email, the sock part is just the wrapper on top of OpenThread.

I was thinking and probably it's better to merge these 2 branches and then try to split in the core part and the NCP,FTD,MTD part. Do you agree?

Cheers!

**Pull request merged**
